<?php

return [
    // CSS Code
    array(
        'key' => 'field_paneflow_css_code',
        'label' => 'CSS Code',
        'name' => 'paneflow_css_code',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Wklej zawartość pliku .min.css slidera',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 10,
        'placeholder' => '/* CSS code */',
        'new_lines' => '',
        'allow_in_bindings' => 0,
    ),

    // JS Code
    array(
        'key' => 'field_paneflow_js_code',
        'label' => 'JS Code',
        'name' => 'paneflow_js_code',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Wklej zawartość pliku .min.js slidera',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 10,
        'placeholder' => '/* JavaScript code */',
        'new_lines' => '',
        'allow_in_bindings' => 0,
    ),

    // HTML Original
    array(
        'key' => 'field_paneflow_html_original',
        'label' => 'HTML Original',
        'name' => 'paneflow_html_original',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Wklej zawartość pliku .html slidera. URLe z cdn.paneflow.com zostaną automatycznie wykryte.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 15,
        'placeholder' => '<!-- HTML code -->',
        'new_lines' => '',
        'allow_in_bindings' => 0,
    ),

    // Media Mapping Repeater
    array(
        'key' => 'field_paneflow_media_mapping',
        'label' => 'Mapowanie Mediów CDN → WordPress',
        'name' => 'paneflow_media_mapping',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => 'Automatycznie wykryte URLe z CDN. Wybierz zamienniki z biblioteki WordPress.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'table',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Dodaj mapowanie',
        'rows_per_page' => 20,
        'sub_fields' => array(
            array(
                'key' => 'field_paneflow_cdn_url',
                'label' => 'URL CDN',
                'name' => 'cdn_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
                'disabled' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_paneflow_media_type',
                'label' => 'Typ',
                'name' => 'media_type',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '15',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => 1,
                'disabled' => 0,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_paneflow_wp_media',
                'label' => 'Media WordPress',
                'name' => 'wp_media',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '45',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
            ),
        ),
        'allow_in_bindings' => 0,
    ),

    // HTML Processed (readonly)
    array(
        'key' => 'field_paneflow_html_processed',
        'label' => 'HTML Przetworzony (po zamianie URLi)',
        'name' => 'paneflow_html_processed',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Automatycznie generowany HTML z zamienionymi URLami. To pole jest tylko do odczytu.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 15,
        'placeholder' => '',
        'new_lines' => '',
        'readonly' => 1,
        'disabled' => 1,
        'allow_in_bindings' => 0,
    ),

    // Extracted CSS (readonly)
    array(
        'key' => 'field_paneflow_extracted_css',
        'label' => 'CSS Wyciągnięty z HTML (z tagów <style>)',
        'name' => 'paneflow_extracted_css',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Automatycznie wyciągnięty CSS z tagów &lt;style&gt; w HTML. Tylko do odczytu.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 10,
        'placeholder' => '',
        'new_lines' => '',
        'readonly' => 1,
        'disabled' => 1,
        'allow_in_bindings' => 0,
    ),

    // Extracted JS (readonly)
    array(
        'key' => 'field_paneflow_extracted_js',
        'label' => 'JS Wyciągnięty z HTML (z tagów <script>)',
        'name' => 'paneflow_extracted_js',
        'aria-label' => '',
        'type' => 'textarea',
        'instructions' => 'Automatycznie wyciągnięty JavaScript z tagów &lt;script&gt; w HTML. Tylko do odczytu.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'rows' => 10,
        'placeholder' => '',
        'new_lines' => '',
        'readonly' => 1,
        'disabled' => 1,
        'allow_in_bindings' => 0,
    ),
];