<?php

return [
    array(
        'key' => 'field_698d8a9fb35bd',
        'label' => 'Style CSS',
        'name' => 'paneflow_style_css',
        'aria-label' => '',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => 'css',
        'allow_in_bindings' => 0,
    ),
    array(
        'key' => 'field_698d8abeb35be',
        'label' => 'Plik JS',
        'name' => 'paneflow_script_js',
        'aria-label' => '',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => 'js',
        'allow_in_bindings' => 0,
    ),
    array(
        'key' => 'field_698d8aedb35bf',
        'label' => 'Plik HTML',
        'name' => 'paneflow_html_file',
        'aria-label' => '',
        'type' => 'file',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_size' => '',
        'max_size' => '',
        'mime_types' => 'html',
        'allow_in_bindings' => 0,
    ),
];