<?php
$fields =  array(

    array(
        'key' => 'field_698dc7a43deef',
        'label' => 'Nagłówek',
        'name' => 'header',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_698dc7b53def0',
        'label' => 'Treść główna',
        'name' => 'main_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => false,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
    ),
    array(
        'key' => 'field_698dc8423def5',
        'label' => 'Tło bloku',
        'name' => 'main_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
    ),
    array(
        'key' => 'field_698dc8653def6',
        'label' => 'Pozycja tła',
        'name' => 'main_image_position',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'top_left' => 'góra - lewo',
            'top_right' => 'góra - prawo',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
        'create_options' => 0,
        'save_options' => 0,
    ),
    array(
        'key' => 'field_698f0451d5164',
        'label' => 'Panele',
        'name' => 'panels',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Dodaj panel',
        'rows_per_page' => 20,
        'sub_fields' => array(
            array(
                'key' => 'field_698f0464d5165',
                'label' => 'Tytuł',
                'name' => 'title',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_698f0451d5164',
            ),
            array(
                'key' => 'field_698f046cd5166',
                'label' => 'Tekst',
                'name' => 'text',
                'aria-label' => '',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
                'parent_repeater' => 'field_698f0451d5164',
            ),
            array(
                'key' => 'field_698f0478d5167',
                'label' => 'Link',
                'name' => 'link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'allow_in_bindings' => 0,
                'parent_repeater' => 'field_698f0451d5164',
            ),
            array(
                'key' => 'field_698f0486d5168',
                'label' => 'Tło',
                'name' => 'background',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'medium',
                'parent_repeater' => 'field_698f0451d5164',
            ),
        ),
    ),
);
return $fields;