<?php
$fields =  array(
    array(
        'key' => 'field_698dc7a43deef',
        'label' => 'Nagłówek',
        'name' => 'header',
        'aria-label' => '',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'maxlength' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_698dc7b53def0',
        'label' => 'Treść główna',
        'name' => 'main_content',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => false,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
    ),
    array(
        'key' => 'field_698dc8423def5',
        'label' => 'Tło bloku',
        'name' => 'main_image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
    ),
    array(
        'key' => 'field_698dc8653def6',
        'label' => 'Pozycja tła',
        'name' => 'main_image_position',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'top_left' => 'góra - lewo',
            'top_right' => 'góra - prawo',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
        'create_options' => 0,
        'save_options' => 0,
    ),
    array(
        'key' => 'field_698ec928c6aa9',
        'label' => 'Obrazy',
        'name' => 'paints',
        'aria-label' => '',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'post_type' => array(
            0 => 'paint',
        ),
        'post_status' => '',
        'taxonomy' => '',
        'filters' => array(
            0 => 'search',
            1 => 'post_type',
            2 => 'taxonomy',
        ),
        'return_format' => 'id',
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'elements' => '',
        'bidirectional' => 0,
        'bidirectional_target' => array(
        ),
    ),
    array(
        'key' => 'field_698dc91d3deff',
        'label' => 'Główne ustawienia animacji',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ),
    array(
        'key' => 'field_698dc92c3df00',
        'label' => 'Włącz animację',
        'name' => 'animation_enable',
        'aria-label' => '',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'allow_in_bindings' => 0,
        'ui_on_text' => 'Tak',
        'ui_off_text' => 'Nie',
        'ui' => 1,
    ),
    array(
        'key' => 'field_698dc94e3df01',
        'label' => 'Długość przewijania sekcji',
        'name' => 'scroll_length',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
            array(
                array(
                    'field' => 'field_698dc92c3df00',
                    'operator' => '==',
                    'value' => '1',
                ),
            ),
        ),
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => 2000,
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ),
);
return $fields;