<?php
$fields =  array(
    array(
        'key' => 'field_694407f7c5f0d',
        'label' => 'Bloki',
        'name' => 'blocks',
        'aria-label' => '',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'layout' => 'block',
        'pagination' => 0,
        'min' => 0,
        'max' => 0,
        'collapsed' => '',
        'button_label' => 'Dodaj wiersz',
        'rows_per_page' => 20,
        'sub_fields' => array(
            array(
                'key' => 'field_69440812c5f0e',
                'label' => 'Obraz',
                'name' => 'image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'allow_in_bindings' => 0,
                'preview_size' => 'medium',
                'parent_repeater' => 'field_694407f7c5f0d',
            ),
            array(
                'key' => 'field_6944082fc5f0f',
                'label' => 'Tekst',
                'name' => 'text',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'parent_repeater' => 'field_694407f7c5f0d',
            ),
            array(
                'key' => 'field_6944083dc5f10',
                'label' => 'Link',
                'name' => 'link',
                'aria-label' => '',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'allow_in_bindings' => 0,
                'parent_repeater' => 'field_694407f7c5f0d',
            ),
            array(
                'key' => 'field_69440847c5f11',
                'label' => 'Podział',
                'name' => 'divide',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '50-50' => '50% obraz - 50% tekst',
                    '25-75' => '25% obraz - 75% tekst',
                    '75-25' => '75% obraz - 25% tekst',
                ),
                'default_value' => false,
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
                'create_options' => 0,
                'save_options' => 0,
                'parent_repeater' => 'field_694407f7c5f0d',
            ),
            array(
                'key' => 'field_694408c93228f',
                'label' => 'Kolejność',
                'name' => 'order',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui_off_text' => 'Obraz po lewej',
                'ui_on_text' => 'Obraz po prawej',
                'ui' => 1,
                'parent_repeater' => 'field_694407f7c5f0d',
            ),
        ),
    ),
);
return $fields;