<?php
$fields =  array(
    array(
        'key' => 'field_698c2b225c37b',
        'label' => 'Grafika',
        'name' => 'image',
        'aria-label' => '',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'return_format' => 'id',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
        'allow_in_bindings' => 0,
        'preview_size' => 'medium',
    ),
    array(
        'key' => 'field_698c2b405c37c',
        'label' => 'Tekst',
        'name' => 'text',
        'aria-label' => '',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'allow_in_bindings' => 0,
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
    ),
    array(
        'key' => 'field_698c2b4f5c37d',
        'label' => 'Kierunek',
        'name' => 'direction',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            'image_on_right' => 'Grafika po prawej',
            'image_on_left' => 'Grafika po lewej',
        ),
        'default_value' => 'image_on_right',
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
        'create_options' => 0,
        'save_options' => 0,
    ),
    array(
        'key' => 'field_698c2bc75c37e',
        'label' => 'Układ',
        'name' => 'ratio',
        'aria-label' => '',
        'type' => 'select',
        'instructions' => 'Szerokości komponentów - obraz / tekst',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'choices' => array(
            '50_50' => '50% / 50%',
            '25_75' => '25% / 75%',
            '75_25' => '75% / 25%',
            '33_66' => '33% / 66%',
            '66_33' => '66% / 33%',
        ),
        'default_value' => false,
        'return_format' => 'value',
        'multiple' => 0,
        'allow_null' => 0,
        'allow_in_bindings' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
        'create_options' => 0,
        'save_options' => 0,
    ),
    array(
        'key' => 'field_698c2c8898a67',
        'label' => 'Ustawienia dodatkowe',
        'name' => '',
        'aria-label' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
    ),
    array(
        'key' => 'field_698c2cbe98a68',
        'label' => 'Dodatkowy odstęp - góra [dektop]',
        'name' => 'padding_top_desktop',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_698c2cf998a69',
        'label' => 'Dodatkowy odstęp - góra [mobile]',
        'name' => 'padding_top_mobile',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_698c2d4298a6a',
        'label' => 'Dodatkowy odstęp - dół [dektop]',
        'name' => 'padding_bottom_desktop',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ),
    array(
        'key' => 'field_698c2d6998a6b',
        'label' => 'Dodatkowy odstęp - dół [mobile]',
        'name' => 'padding_bottom_mobile',
        'aria-label' => '',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
            'width' => '50',
            'class' => '',
            'id' => '',
        ),
        'default_value' => '',
        'min' => '',
        'max' => '',
        'allow_in_bindings' => 0,
        'placeholder' => '',
        'step' => '',
        'prepend' => '',
        'append' => '',
    ),
);
return $fields;